# Example configuration file that:
#  - Has a private registry
#  - Ignores lodash dependency
#  - Disables version-updates
#  - Defines a group by package name, for security updates for golang dependencies

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web/Reusehive"
    schedule:
      interval: "daily"
  
